### ISSUE TITLE
Add support for variable substituition in npm run scripts 

### ISSUE THREAD

**Issue by dagadbm** [dotenvx/docs#9]
Although this exists: https://dotenvx.com/docs/advanced/run-shell-expansion

I dont think it is a very good solution as it always implies a linux machine underneath.

A better documentation for this would be to adapt it from here: https://github.com/entropitor/dotenv-cli?tab=readme-ov-file#variable-expansion-in-the-command

**Comment by motdotla** [comment]
agree. would you like to update that docs page to add that info @dagadbm? otherwise, i will try to get to this as soon as possible. thanks for raising this!

**Comment by motdotla** [comment]
added more details: https://dotenvx.com/docs/advanced/run-shell-expansion
